"""A question that plants its own answer is not evidence, and this refuses to send it.

The whole reach of this system rests on independence. `cfas/waggle.py` adds
log-likelihood ratios, and log-likelihood ratios only add for observations that are
conditionally independent given the hypothesis. List, Elsholtz and Seeley showed the
same thing in the swarm: reliable collective choice needs recruits who assess a site
for themselves, and tip a colony too far toward copying and it converges on whatever
was found first regardless of quality.

So when the recruiter asks a resident what they can see, the question must not tell
them what to see. Ask "we hear water reach chest for your area, na true?" and the
reply is an echo of the report that prompted it, and counting it toward the threshold
double-counts one observation. The failure is quiet and total: the likelihood model in
the design document assumes `P(band | cell state)`, a report generated by the water. A
leading question replaces it with `P(band | question)`, so every Lambda downstream is
the wrong number while the arithmetic carries on looking healthy.

That is too important to leave to an instruction, so it is not one. This is a filter
every outbound question passes through, on the *poka-yoke* principle: make the mistake
impossible instead of discouraging it.

**The blocklist is the measurement lexicon itself.** Every cue `cfas/hazard.py` can
read out of a reply is a word the question may not contain, which is not a coincidence
but the whole design: the two lists cannot drift apart because they are one list. Add a
depth cue to the hazard model and this filter starts rejecting questions containing it
on the same commit, in all three languages, because the lexicon is trilingual and the
matcher is shared.
"""
from __future__ import annotations

from itertools import chain

from .hazard import DEBRIS_CUES, DEPTH_CUES, VELOCITY_CUES, _normalise, _present

# Naming a band is as leading as naming a body part: "is it high?" invites a yes.
BAND_WORDS = ("low", "medium", "high", "severe", "danger", "dangerous",
              "flood", "flooded", "flooding", "warning", "alert", "emergency")

# Constructions that carry an expectation even with no cue word in them. "Is it true
# that", "we hear", "somebody said" all hand the resident a proposition to agree with
# instead of asking them to look.
LEADING_PHRASES = ("is it true", "na true", "we hear", "we heard", "is it correct",
                   "somebody said", "someone said", "people say", "dem say",
                   "confirm that", "can you confirm", "are you sure", "abi",
                   "right?", "correct?", "njẹ́ òtítọ́")

MAX_WORDS = 20


def banned_terms() -> list[str]:
    """Every word a neutral question may not contain, deduplicated.

    Built from the hazard lexicon at call time rather than frozen at import, so a cue
    added to the measurement model is covered here without anyone remembering to.
    """
    terms = set(chain(*DEPTH_CUES.values(), *VELOCITY_CUES.values(),
                      DEBRIS_CUES, BAND_WORDS))
    return sorted(terms, key=len, reverse=True)


def is_neutral(question: str) -> tuple[bool, str | None]:
    """Would this question let the resident answer from the water rather than from us?

    Returns (True, None) when the question is safe to send, and (False, reason) when
    it is not, where `reason` names the offending term so the caller can rewrite
    rather than merely fail. A recruiter that is told which word it tripped on writes
    a better second attempt than one told only that it was refused.
    """
    text = str(question).strip()
    if not text:
        return False, "empty"
    if len(text.split()) > MAX_WORDS:
        return False, "too long"

    norm = _normalise(text)
    for phrase in LEADING_PHRASES:
        if _normalise(phrase) in norm:          # substring: these are constructions
            return False, phrase
    for word in banned_terms():
        if _present(norm, _normalise(word)):    # whole word: these are cues
            return False, word
    if "?" not in text:
        return False, "not a question"
    return True, None


def refusal_note(reason: str) -> str:
    """What the recruiter is told when a question is refused. Explains, never scolds."""
    if reason == "too long":
        return (f"Refused: over {MAX_WORDS} words. A person standing in moving water "
                f"reads the first few words and no more.")
    if reason == "not a question":
        return "Refused: ask something. A statement invites agreement, not observation."
    if reason == "empty":
        return "Refused: no question given."
    return (f"Refused: contains '{reason}', which the measurement model reads as a cue. "
            f"Asking it hands the resident the answer, and their reply then carries no "
            f"independent evidence. Ask what they can see instead.")
